In [63]:
import pandas as pd
import numpy as np

In [64]:
customers_df=pd.read_csv (r"C:\Data Analusis Course\wk8\wk8-customers.csv")
products_df = pd.read_csv(r"C:\Data Analusis Course\wk8\wk8-products.csv")
stores_df =pd.read_csv(r"C:\Data Analusis Course\wk8\wk8-stores.csv")
sales_df =pd.read_csv(r"C:\Data Analusis Course\wk8\wk8-sales.csv")
inventory_df =pd.read_csv(r"C:\Data Analusis Course\wk8\wk8-inventory.csv")

In [65]:
print(customers_df.head(), "\n")
print(products_df.head(), "\n")
print(stores_df.head(), "\n")
print(sales_df.head(), "\n")
print(inventory_df.head(), "\n")

   customer_id first_name last_name                  email           phone  \
0            1      James     Smith  james.smith@gmail.com    555-123-4567
1            2       Mary   Johnson                    NaN    212.555.6789
2            3       John  Williams    jwilliams@yahoo.com  (555) 987-6543
3            4   Patricia     Brown     pbrown@hotmail.com      5551234567
4            5     Robert     Jones     rjones23@gmail.com    555-987-3456

        address         city       state    zip_code registration_date
0   123 Main St     New York          NY       10001         3/15/2021
1  456 Park Ave     New York          NY       10022         11/2/2020
2  789 Broadway  Los Angeles  California  90001-1234         5/20/2021
3    321 Elm St      Chicago          IL       60601               NaN
4   555 Pine St      Houston          TX       77002         9/12/2020

   product_id        product_name     category  subcategory    brand    price  \
0           1     Apple iPhone 13  Electronics  Smartphones    Apple   899.99
1           2  Samsung Galaxy S21  electronics  Smartphones  Samsung   799.99
2           3     Sony WH-1000XM4  ELECTRONICS   Headphones     Sony   349.99
3           4         Dell XPS 13  Electronics      Laptops     Dell  1299.99
4           5    Nike Classic Tee     Clothing       Shirts     Nike    24.99

     cost  weight
0  649.99    0.45
1  539.99    0.50
2  210.00    0.60
3  899.99    2.80
4   12.50    0.20

   store_id         store_name           address         city  state zip_code  \
0         1        City Center   123 Retail Blvd     New York     NY    10001
1         2    Mall of Chicago  456 Shopping Ave      Chicago     IL    60611
2         3  Los Angeles Plaza   789 Commerce St  Los Angeles     CA    90001
3         4   Houston Galleria       321 Main St      Houston  Texas    77002
4         5     Phoenix Outlet     654 Desert Rd      Phoenix     AZ    85001

      region  size_sqft opening_date
0  Northeast    32500.0   2005-05-20
1    Midwest    45000.0   2007-08-15
2       West    55000.0   2004-03-10
3  Southwest        NaN   2008-11-05
4  Southwest    18500.0   2010-06-30

   sale_id        date  store_id  customer_id  product_id  quantity    total  \
0        1  2022-01-15       3.0           12           5         2    49.98
1        2  2022-01-16       1.0            5          10         1    49.99
2        3  2022-01-18       2.0            8           3         1   349.99
3        4  2022-01-20       4.0           20           7         1   349.99
4        5  2022-01-22       5.0            3          15         1  1599.99

  payment_method
0    Credit Card
1    credit card
2     DEBIT CARD
3           Cash
4             CC

   inventory_id  store_id  product_id  quantity_in_stock last_restock_date  \
0             1         1           1                 25        2022-10-15
1             2         1           5                 42        2022-11-02
2             3         1          10                 18        2022-09-30
3             4         1          15                  5        2022-10-20
4             5         1          20                 12               NaN

   reorder_level
0           10.0
1           15.0
2            8.0
3           10.0
4           15.0

In [66]:
print(customers_df.info(), "\n")
print(customers_df.describe(), "\n")

<class 'pandas.DataFrame'>
RangeIndex: 31 entries, 0 to 30
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   customer_id        31 non-null     int64
 1   first_name         31 non-null     str
 2   last_name          31 non-null     str
 3   email              28 non-null     str
 4   phone              29 non-null     str
 5   address            31 non-null     str
 6   city               31 non-null     str
 7   state              31 non-null     str
 8   zip_code           30 non-null     str
 9   registration_date  28 non-null     str
dtypes: int64(1), str(9)
memory usage: 5.0 KB
None

       customer_id
count    31.000000
mean     15.838710
std       8.858505
min       1.000000
25%       8.500000
50%      16.000000
75%      23.500000
max      30.000000

In [67]:
print(products_df.info(), "\n")
print(products_df.describe(), "\n")

<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    30 non-null     int64
 1   product_name  30 non-null     str
 2   category      30 non-null     str
 3   subcategory   30 non-null     str
 4   brand         30 non-null     str
 5   price         30 non-null     float64
 6   cost          30 non-null     float64
 7   weight        28 non-null     float64
dtypes: float64(3), int64(1), str(4)
memory usage: 3.3 KB
None

       product_id        price         cost     weight
count   30.000000    30.000000    30.000000  28.000000
mean    15.500000   191.724000   203.159000   3.835714
std      8.803408   452.483576   278.924138   5.693236
min      1.000000 -1599.990000     1.800000   0.200000
25%      8.250000    46.990000    28.375000   0.500000
50%     15.500000   134.990000    82.500000   1.150000
75%     22.750000   322.490000   236.250000   3.750000
max     30.000000  1299.990000  1100.000000  25.000000

In [68]:
print(stores_df.info(), "\n")
print(stores_df.describe(), "\n")

<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   store_id      15 non-null     int64
 1   store_name    15 non-null     str
 2   address       15 non-null     str
 3   city          15 non-null     str
 4   state         15 non-null     str
 5   zip_code      15 non-null     str
 6   region        15 non-null     str
 7   size_sqft     13 non-null     float64
 8   opening_date  14 non-null     str
dtypes: float64(1), int64(1), str(7)
memory usage: 2.1 KB
None

        store_id     size_sqft
count  15.000000     13.000000
mean    8.000000  30653.846154
std     4.472136  11342.002717
min     1.000000  16500.000000
25%     4.500000  22000.000000
50%     8.000000  29000.000000
75%    11.500000  35000.000000
max    15.000000  55000.000000

In [69]:
print(sales_df.info(), "\n")
print(sales_df.describe(), "\n")

<class 'pandas.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   sale_id         40 non-null     int64
 1   date            39 non-null     str
 2   store_id        39 non-null     float64
 3   customer_id     40 non-null     int64
 4   product_id      40 non-null     int64
 5   quantity        40 non-null     int64
 6   total           40 non-null     float64
 7   payment_method  39 non-null     str
dtypes: float64(2), int64(4), str(2)
memory usage: 3.3 KB
None

         sale_id   store_id  customer_id  product_id   quantity        total
count  40.000000  39.000000    40.000000   40.000000  40.000000    40.000000
mean   20.500000   6.487179    14.075000   13.500000   1.625000   352.296500
std    11.690452   4.235637     8.303189    8.857852   0.952392   377.625776
min     1.000000   1.000000     1.000000    1.000000   1.000000    19.980000
25%    10.750000   3.000000     6.750000    5.750000   1.000000    99.737500
50%    20.500000   6.000000    13.500000   11.500000   1.000000   229.985000
75%    30.250000   9.500000    20.250000   21.250000   2.000000   352.487500
max    40.000000  15.000000    29.000000   30.000000   5.000000  1599.990000

In [70]:
print(inventory_df.info(), "\n")
print(inventory_df.describe(), "\n")

<class 'pandas.DataFrame'>
RangeIndex: 75 entries, 0 to 74
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   inventory_id       75 non-null     int64
 1   store_id           75 non-null     int64
 2   product_id         75 non-null     int64
 3   quantity_in_stock  75 non-null     int64
 4   last_restock_date  66 non-null     str
 5   reorder_level      69 non-null     float64
dtypes: float64(1), int64(4), str(1)
memory usage: 4.3 KB
None

       inventory_id   store_id  product_id  quantity_in_stock  reorder_level
count     75.000000  75.000000   75.000000          75.000000      69.000000
mean      38.000000   8.000000   12.733333          22.640000      12.681159
std       21.794495   4.349588    7.179801          13.923187       3.327659
min        1.000000   1.000000    1.000000           0.000000       8.000000
25%       19.500000   4.000000    6.500000          15.000000      10.000000
50%       38.000000   8.000000   13.000000          25.000000      10.000000
75%       56.500000  12.000000   19.000000          33.500000      15.000000
max       75.000000  15.000000   25.000000          45.000000      20.000000

In [71]:
customers_df.isnull().sum()

customer_id          0
first_name           0
last_name            0
email                3
phone                2
address              0
city                 0
state                0
zip_code             1
registration_date    3
dtype: int64

In [72]:
products_df.isnull().sum()

product_id      0
product_name    0
category        0
subcategory     0
brand           0
price           0
cost            0
weight          2
dtype: int64

In [73]:
stores_df.isnull().sum()

store_id        0
store_name      0
address         0
city            0
state           0
zip_code        0
region          0
size_sqft       2
opening_date    1
dtype: int64

In [74]:
sales_df.isnull().sum()

sale_id           0
date              1
store_id          1
customer_id       0
product_id        0
quantity          0
total             0
payment_method    1
dtype: int64

In [75]:
inventory_df.isnull().sum()

inventory_id         0
store_id             0
product_id           0
quantity_in_stock    0
last_restock_date    9
reorder_level        6
dtype: int64

In [76]:
customers_df.dtypes

customer_id          int64
first_name             str
last_name              str
email                  str
phone                  str
address                str
city                   str
state                  str
zip_code               str
registration_date      str
dtype: object

In [77]:
products_df.dtypes

product_id        int64
product_name        str
category            str
subcategory         str
brand               str
price           float64
cost            float64
weight          float64
dtype: object

In [78]:
stores_df.dtypes

store_id          int64
store_name          str
address             str
city                str
state               str
zip_code            str
region              str
size_sqft       float64
opening_date        str
dtype: object

In [79]:
stores_df.dtypes

store_id          int64
store_name          str
address             str
city                str
state               str
zip_code            str
region              str
size_sqft       float64
opening_date        str
dtype: object

In [80]:
inventory_df.dtypes

inventory_id           int64
store_id               int64
product_id             int64
quantity_in_stock      int64
last_restock_date        str
reorder_level        float64
dtype: object

In [81]:
p=products_df['product_name'].unique()

In [82]:
print(p)
#How many unique products are in the product catalog?
print('there is', len(p),'unique products')

<ArrowStringArray>
[               'Apple iPhone 13',             'Samsung Galaxy S21',
                'Sony WH-1000XM4',                    'Dell XPS 13',
               'Nike Classic Tee',              'Levi's Slim Jeans',
         'KitchenAid Stand Mixer',         'Cuisinart Coffee Maker',
              'IKEA Malm Dresser',    'Penguin Classics Collection',
          'The North Face Jacket',             'Nike Running Shoes',
             'LEGO Star Wars Set',       'L'Oreal Revitalift Cream',
              'Apple MacBook Pro',           'Bose QuietComfort 45',
 'Hershey's Chocolate Assortment',             'Adidas Track Pants',
              'Kindle Paperwhite',               'Dyson V11 Vacuum',
              'Outdoor Gas Grill',       'Calvin Klein Men's Shirt',
           'Coleman Camping Tent',       'Mattel Barbie Dreamhouse',
           'Neutrogena Face Wash',           'General Mills Cereal',
             'Sony PlayStation 5',            'HP Wireless Printer',
                'Zara Maxi Dress',          'Columbia Winter Parka']
Length: 30, dtype: str
there is 30 unique products

In [83]:
#top 5 most expensive products
products_df.sort_values(by='price', ascending=False).head(5)

,product_id,product_name,category,subcategory,brand,price,cost,weight
3,4,Dell XPS 13,Electronics,Laptops,Dell,1299.99,899.99,2.80
0,1,Apple iPhone 13,Electronics,Smartphones,Apple,899.99,649.99,0.45
1,2,Samsung Galaxy S21,electronics,Smartphones,Samsung,799.99,539.99,0.50
19,20,Dyson V11 Vacuum,HOME & KITCHEN,Appliances,Dyson,599.99,375.00,6.70
26,27,Sony PlayStation 5,Electronics,Gaming,Sony,499.99,399.00,4.50

In [84]:
#Which store has the largest floor space?
largest_store=stores_df.sort_values('size_sqft', ascending=False).head(1)
print('largest  store is',largest_store['store_name'])

largest  store is 2    Los Angeles Plaza
Name: store_name, dtype: str

In [85]:
#What is the distribution of customers by state?
customer_counts = customers_df['state'].value_counts()
print(customer_counts)

state
TX                4
CA                3
NY                2
California        1
IL                1
AZ                1
PA                1
Texas             1
FL                1
OH                1
North Carolina    1
IN                1
Washington        1
CO                1
MA                1
Oregon            1
NV                1
MI                1
TN                1
Maryland          1
MD                1
KY                1
WI                1
NM                1
MO                1
Name: count, dtype: int64

In [86]:
customers_df.isnull().sum()

customer_id          0
first_name           0
last_name            0
email                3
phone                2
address              0
city                 0
state                0
zip_code             1
registration_date    3
dtype: int64

In [87]:
customers_df['registration_date']=customers_df['registration_date'].bfill

In [88]:
print(customers_df.isnull().sum())
print("I didn't fill email, phone number and zip code with any thing because I think  this will miss the data, I replaced the registration date with previous date")

customer_id          0
first_name           0
last_name            0
email                3
phone                2
address              0
city                 0
state                0
zip_code             1
registration_date    0
dtype: int64
I didn't fill email, phone number and zip code with any thing because I think  this will miss the data, I replaced the registration date with previous date

In [89]:
products_df.isnull().sum()

product_id      0
product_name    0
category        0
subcategory     0
brand           0
price           0
cost            0
weight          2
dtype: int64

In [90]:
products_df['weight']=products_df['weight'].fillna(products_df['weight'].mean())

In [91]:
print(products_df.isnull().sum())
print("====================================","\n")
print("There is No null Values Now in Products")

product_id      0
product_name    0
category        0
subcategory     0
brand           0
price           0
cost            0
weight          0
dtype: int64
====================================

There is No null Values Now in Products

In [92]:
stores_df.isnull().sum()

store_id        0
store_name      0
address         0
city            0
state           0
zip_code        0
region          0
size_sqft       2
opening_date    1
dtype: int64

In [93]:
stores_df['size_sqft']=stores_df['size_sqft'].fillna(stores_df['size_sqft'].mean())

In [94]:
stores_df['opening_date']=stores_df['opening_date'].bfill()

In [95]:
stores_df.isnull().sum()
print(stores_df.isnull().sum())
print('=================================')
print("Stores has No Missing Values Now")

store_id        0
store_name      0
address         0
city            0
state           0
zip_code        0
region          0
size_sqft       0
opening_date    0
dtype: int64
=================================
Stores has No Missing Values Now

In [96]:
sales_df.isnull().sum()

sale_id           0
date              1
store_id          1
customer_id       0
product_id        0
quantity          0
total             0
payment_method    1
dtype: int64

In [97]:
sales_df['date']=sales_df['date'].bfill

In [98]:
sales_df['payment_method']=sales_df['payment_method'].bfill

In [99]:
sales_df['store_id']=sales_df['store_id'].bfill

In [100]:
print(sales_df.isnull().sum())
print('=================================','\n')
print('No Null Values in Sales Now')

sale_id           0
date              0
store_id          0
customer_id       0
product_id        0
quantity          0
total             0
payment_method    0
dtype: int64
=================================

No Null Values in Sales Now

In [101]:
inventory_df.isnull().sum()

inventory_id         0
store_id             0
product_id           0
quantity_in_stock    0
last_restock_date    9
reorder_level        6
dtype: int64

In [102]:
inventory_df['reorder_level'].mode()

0    10.0
Name: reorder_level, dtype: float64

In [103]:
inventory_df['last_restock_date']=inventory_df['last_restock_date'].ffill()

In [104]:
inventory_df['reorder_level']=inventory_df['reorder_level'].fillna(10)

In [105]:
print(inventory_df.isnull().sum())
print("===============================","\n")
print("No null Values in Inventory Now")

inventory_id         0
store_id             0
product_id           0
quantity_in_stock    0
last_restock_date    0
reorder_level        0
dtype: int64
===============================

No null Values in Inventory Now

In [108]:
customers_df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
dtype: bool

In [126]:
#I will remove the duplicate if the firt and last name and city are the same
# and there is one (26 is true)
customers_df[['first_name','last_name','city']].duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26     True
27    False
28    False
29    False
30    False
dtype: bool

In [141]:
customers_df[['first_name','last_name','city']].drop_duplicates(keep='first')
#it is the same customer but depending on other information like the phone or state didn't help because the information written in a different way,so looking at first and last name and city helped make sure it is the same person so it duplicated

     first_name  last_name           city
0         James      Smith       New York
1          Mary    Johnson       New York
2          John   Williams    Los Angeles
3      Patricia      Brown        Chicago
4        Robert      Jones        Houston
5      Jennifer     Miller        Phoenix
6       Michael      Davis   Philadelphia
7         Linda     Garcia    San Antonio
8       William  Rodriguez      San Diego
9     Elizabeth     Wilson         Dallas
10        David   Martinez       San Jose
11      Barbara   Anderson         Austin
12      Richard     Taylor   Jacksonville
13        Susan     Thomas     Fort Worth
14       Joseph  Hernandez       Columbus
15      Jessica      Moore      Charlotte
16       Thomas     Martin  San Francisco
17        Sarah    Jackson   Indianapolis
18      Charles   Thompson        Seattle
19        Karen      White         Denver
20  Christopher      Lopez         Boston
21        Nancy        Lee       Portland
22       Daniel   Gonzalez      Las Vegas
23     Margaret     Harris        Detroit
24      Matthew      Clark      Nashville
25        Betty      Lewis      Baltimore
27       Steven   Robinson     Louisville
28      Dorothy     Walker      Milwaukee
29      Anthony      Perez    Albuquerque
30         Lisa       Hall    Kansas City

In [143]:
customers_df=customers_df.drop(26)

In [144]:
customers_df

,customer_id,first_name,last_name,email,phone,address,city,state,zip_code,registration_date
0,1,James,Smith,james.smith@gmail.com,555-123-4567,123 Main St,New York,NY,10001,<bound method NDFrame.bfill of 0 3/15/202...
1,2,Mary,Johnson,NaN,212.555.6789,456 Park Ave,New York,NY,10022,<bound method NDFrame.bfill of 0 3/15/202...
2,3,John,Williams,jwilliams@yahoo.com,(555) 987-6543,789 Broadway,Los Angeles,California,90001-1234,<bound method NDFrame.bfill of 0 3/15/202...
3,4,Patricia,Brown,pbrown@hotmail.com,5551234567,321 Elm St,Chicago,IL,60601,<bound method NDFrame.bfill of 0 3/15/202...
4,5,Robert,Jones,rjones23@gmail.com,555-987-3456,555 Pine St,Houston,TX,77002,<bound method NDFrame.bfill of 0 3/15/202...
5,6,Jennifer,Miller,jmiller@outlook.com,NaN,898 Cedar Dr,Phoenix,AZ,85001,<bound method NDFrame.bfill of 0 3/15/202...
6,7,Michael,Davis,mdavis@gmail.com,555.432.7654,742 Maple Ave,Philadelphia,PA,19103,<bound method NDFrame.bfill of 0 3/15/202...
7,8,Linda,Garcia,lgarcia@yahoo.com,555 876 2345,953 Oak Ln,San Antonio,Texas,78205,<bound method NDFrame.bfill of 0 3/15/202...
8,9,William,Rodriguez,wrodriguez@hotmail.com,5558889999,159 Washington Blvd,San Diego,CA,92101,<bound method NDFrame.bfill of 0 3/15/202...
9,10,Elizabeth,Wilson,ewilson@gmail.com,(555) 333-2211,753 Lincoln Rd,Dallas,TX,75201,<bound method NDFrame.bfill of 0 3/15/202...
10,11,David,Martinez,dmartinez@yahoo.com,555-111-3333,246 Jefferson Ave,San Jose,CA,95113,<bound method NDFrame.bfill of 0 3/15/202...
11,12,Barbara,Anderson,NaN,555.444.9876,135 Madison St,Austin,TX,NaN,<bound method NDFrame.bfill of 0 3/15/202...
12,13,Richard,Taylor,rtaylor@outlook.com,5552223333,864 Adams Ct,Jacksonville,FL,32202,<bound method NDFrame.bfill of 0 3/15/202...
13,14,Susan,Thomas,sthomas45@gmail.com,NaN,579 Monroe Pl,Fort Worth,TX,76102,<bound method NDFrame.bfill of 0 3/15/202...
14,15,Joseph,Hernandez,jhernandez@yahoo.com,555-777-8888,951 Jackson Dr,Columbus,OH,43215,<bound method NDFrame.bfill of 0 3/15/202...
15,16,Jessica,Moore,jmoore@hotmail.com,555.666.1234,357 Tyler St,Charlotte,North Carolina,28202,<bound method NDFrame.bfill of 0 3/15/202...
16,17,Thomas,Martin,tmartin@gmail.com,(555) 444-5678,159 Polk Ave,San Francisco,CA,94102,<bound method NDFrame.bfill of 0 3/15/202...
17,18,Sarah,Jackson,sjackson@yahoo.com,5557890123,753 Harrison Rd,Indianapolis,IN,46204,<bound method NDFrame.bfill of 0 3/15/202...
18,19,Charles,Thompson,cthompson@outlook.com,555-321-6547,951 Van Buren St,Seattle,Washington,98101,<bound method NDFrame.bfill of 0 3/15/202...
19,20,Karen,White,kwhite88@gmail.com,555.789.4561,357 Fillmore Dr,Denver,CO,80202,<bound method NDFrame.bfill of 0 3/15/202...
20,21,Christopher,Lopez,clopez@yahoo.com,555 456 7890,159 Pierce Ave,Boston,MA,2108,<bound method NDFrame.bfill of 0 3/15/202...
21,22,Nancy,Lee,nlee@hotmail.com,5559876543,753 Hayes Blvd,Portland,Oregon,97201,<bound method NDFrame.bfill of 0 3/15/202...
22,23,Daniel,Gonzalez,dgonzalez@gmail.com,(555) 123-7890,951 Grant St,Las Vegas,NV,89101,<bound method NDFrame.bfill of 0 3/15/202...
23,24,Margaret,Harris,mharris@yahoo.com,555-321-6789,357 Sherman Rd,Detroit,MI,48226,<bound method NDFrame.bfill of 0 3/15/202...
24,25,Matthew,Clark,mclark@outlook.com,555.654.9870,159 Sheridan Dr,Nashville,TN,37201,<bound method NDFrame.bfill of 0 3/15/202...
25,26,Betty,Lewis,betty.lewis@gmail.com,5551597532,753 MacArthur Blvd,Baltimore,Maryland,21202,<bound method NDFrame.bfill of 0 3/15/202...
27,27,Steven,Robinson,srobinson@yahoo.com,555-951-7532,951 Hooker St,Louisville,KY,40202,<bound method NDFrame.bfill of 0 3/15/202...
28,28,Dorothy,Walker,dwalker@hotmail.com,5553579514,357 Halsted Ave,Milwaukee,WI,53202,<bound method NDFrame.bfill of 0 3/15/202...
29,29,Anthony,Perez,NaN,555.753.9512,159 Ashland Dr,Albuquerque,NM,87102,<bound method NDFrame.bfill of 0 3/15/202...
30,30,Lisa,Hall,lhall@gmail.com,(555) 951-7530,753 Morgan St,Kansas City,MO,64101,<bound method NDFrame.bfill of 0 3/15/202...

In [ ]:
#Discussion Questions

In [ ]:
#Key Advantages of Using PandasSpeed:
1-Processes millions of rows instantly by handling entire columns at once.Simplicity:
2-Replaces manual Excel work with short, reusable commands.
3-Flexibility: Merges, reshapes, and filters messy data with minimal code
4-Connections: Links perfectly with graphing tools .

In [145]:
#2. Handling Pattern-Based Missing Data If data is missing for a specific reason, standard averages can fill the results.
filling: Fill missing fields using the average of a specific, relevant group. 
flags: Add a column tracking what was missing to preserve that pattern

In [ ]:
# What types of data quality issues might not be immediately visible through simple DataFrame inspection methods?
Hidden spaces:like "USA " and "USA" look identical but cause matching errors.
Fake text: Placeholder entries like "N/A", "None", or -999 that trick the computer into thinking data is there.
Bad logic: Impossible combinations, like a checkout date that happens before the check-in date.

In [ ]:
#4 How would you document your data cleaning process to ensure reproducibility?
# I wrote notes in my jypyter note work and i wrote these to my personal notes

In [ ]:
#In what scenarios might it be better to remove rows with missing values rather than imputing them?
The row is missing almost all of its information anyway
 The exact answer you are trying to predict is blank.